name: Website Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install html-proofer

      - name: Build site
        run: |
          if [ -f Gemfile ]; then
            bundle install
            bundle exec jekyll build
          else
            jekyll build
          fi

      - name: Test HTML
        run: |
          htmlproofer ./_site \
            --check-html \
            --check-img-http \
            --disable-external \
            --assume-extension \
            --allow-hash-href
